sudo: false
language: cpp

matrix:
  include:
    # - os: linux
    #   compiler: clang
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-trusty-5.0
    #       packages:
    #         - g++-7
    #         - clang-5.0
    #   env: COMPILER='clang++-5.0'
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - ninja-build
            - python3
      env:
        CC='gcc-8'
        CXX='g++-8'
        BUILD_TYPE=Debug

install:
  - travis_retry wget https://cmake.org/files/v3.12/cmake-3.12.3-Linux-x86_64.sh
  - sh ./cmake-3.12.3-Linux-x86_64.sh --prefix=$HOME --skip-license
  - set PATH="$HOME/bin:$PATH"
  - cmake --version

script:
  - mkdir build && cd build
  - cmake .. -GNinja
    -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    -DCMAKE_CXX_COMPILER=$(which $CXX)
    -DCMAKE_C_COMPILER=$(which $C)
  - cmake --build . -j
  - ctest --output-on-failure -j3
