sudo: false
language: shell

matrix:
  include:
    # - os: linux
    #   compiler: clang
    #   addons:
    #     apt:
    #       sources:
    #         - ubuntu-toolchain-r-test
    #         - llvm-toolchain-trusty-5.0
    #       packages:
    #         - g++-7 # Gets newer version of libstdc++ hopefully
    #         - clang-5.0
    #   env: COMPILER='clang++-5.0'
    - os: linux
      # compiler: gcc
      # addons:
      #   apt:
      #     sources:
      #       - ubuntu-toolchain-r-test
      #     packages:
      #       - g++-8
      # env: COMPILER='g++-8'

install:
  - travis_retry wget https://cmake.org/files/v3.12/cmake-3.12.3-Linux-x86_64.sh
  - sh ./cmake-3.12.3-Linux-x86_64.sh --prefix=$HOME/bin
  - ls $HOME/bin

script:
  - mkdir build && cd build
  - cmake --version
