dist: trusty
sudo: false
language: cpp

matrix:
  include:
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - g++-8 # For updated libstdc++
            - clang-7
            - ninja-build
      env:
        C_COMPILER=clang-7
        CXX_COMPILER=clang++-7
        BUILD_TYPE=Debug

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
            - ninja-build
      env:
        C_COMPILER=gcc-8
        CXX_COMPILER=g++-8
        BUILD_TYPE=Debug

before_install:
  export PYENV_VERSION=3.6

install:
  # Install newer cmake
  - travis_retry wget https://cmake.org/files/v3.12/cmake-3.12.3-Linux-x86_64.sh
  - sh ./cmake-3.12.3-Linux-x86_64.sh --prefix=$HOME --skip-license
  - set PATH="$HOME/bin:$PATH"
  - cmake --version
  # Install conan (travis needs this, normally unneeded, since PMM would handle it)
  - pip3 install conan --user
  - conan --version

script:
  - mkdir build && cd build
  - cmake .. -GNinja
    -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    -DCMAKE_C_COMPILER=$C_COMPILER
    -DCMAKE_CXX_COMPILER=$CXX_COMPILER
    -DCMAKE_CXX_STANDARD=17
    -DCMAKE_CXX_EXTENSIONS=OFF
  - cmake --build . -j
  - ctest --output-on-failure
